[package]
name = "tftp_embedded_nal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1"
tftp = "0.1.0"
nb = "1"
embedded-nal = "0.6.0"
heapless = "0.7.16"